from .articulo import ArticuloAdmin
from .autor import AutorAdmin
from .narracion import NarracionAdmin
from .parametro import ParametroAdmin
from .podcast import PodcastAdmin
from .poema import PoemaAdmin
from .social import SocialAdmin
from .suscripcion import SuscripcionAdmin
from .texto import TextoAdmin
from .video import VideoAdmin
